# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    docker run --rm ghcr.io/aquasecurity/trivy:latest -f template --template "@contrib/html.tpl" image python:slim > output.html
  displayName: 'Run Trivy vulnerablity scan'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
- task : PublishTestResult@2
  inputs: 
   testResultsFormat: 'html'
   testResultsFiles: **/output.html
   mergeTestResults: true
   failTaskOnFailedTests: false
   testRunTitle: 'Trivy -Vulnerabilities scan'
  condition: 'always()'