# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# steps:
# - script: |
#     docker run --rm ghcr.io/aquasecurity/trivy:latest -f template --template "@contrib/html.tpl" image python:slim > output.html
#   displayName: 'Run Trivy vulnerablity scan'

- task: Docker@1
  inputs: 
    containerregistrytype: 'Azure Container Registry'
    command: 'docker run --rm ghcr.io/aquasecurity/trivy:latest -f template --template "@contrib/html.tpl" image python:slim > output.html'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'HTML'
    testResultsFiles: '**/output.html'
    mergeTestResults: true
    failTaskOnFailedTests: false
    testRunTitle: 'Trivy - Vulnerabilities Summary'